steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'landscape-photo-agent'
      - '--source=.'
      - '--region=asia-northeast1'
      - '--no-cpu-throttling'
      - '--min-instances=0'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
